<a href="https://colab.research.google.com/github/k-sahaj/Data-Science-Learnings/blob/main/DL/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], columns = ['cgpa', 'profile_score', 'lpa'])
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


This data is generated aisa kyonki apne ko data scaling bhi dhyan me rakhna tha. Additionally, the size is also low bcz its just for learning and grasping the concept.

In [ ]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

     parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
     parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [ ]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

we defined a function to initialize parameters. there are many approaches like giving some random value, giving 1 to W and 0 to b, scaling it down, etc.

In code,np.random.seed ensures ki har baar same hi random number generate ho i.e. If someone else runs the same code with the same NumPy version and the same seed, they'll get the same sequence.

shuru me parameters kuchh naii aur length is length.

loop me har l ke liye weights nikalne hain. Kon se l me kitna hoga decided from that (layer[--], layer[--])

In [ ]:
def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b

  return Z

Iss function me we are just calculating the Oxx i.e. z = (weight) ka transpose multiplied by Previous ka Output + bias


In [ ]:
#Forward Propagation

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2 # idhar // ensures integer value

  for l in range(1, L+1):
    A_prev = A
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]

    # print("A"+str(l-1)+": ", A_prev)
    # print("W"+str(l)+": ", W1)
    # print("b"+str(l)+": ", b1)
    # print("--"*20)

    A = linear_forward(A_prev, W1, b1)
    # print("A"+str(l)+": ", A)
    # print("**"*20)

  return A, A_prev

Idhar A's are nothing but collection of all outputs in that layer. A_prev ke liye pichhle layer ka, and we'll find out iss layer ka A using linear_forward wala function that we just created one cell above.

Thus, this function will return two things-
1. A which is the output
2. A previous which is the output of previous layer and we need that for our partial derivative calculation later in GD and updating.

In [ ]:
#Example check:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X, parameters)

In [ ]:
y_hat = y_hat[0][0]

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X):
  #Iss example me apne paas 9 parameters honge
  #lr = 0.001

  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

  #formula me - - = + ho gayaa
  return parameters


In [ ]:
update_parameters(parameters, y, y_hat, A1, X)


{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

Using this W and b's that we got, do the same thig with other 3 row data changing the w and b's every single time little by little, also calculating loss for every row.

Then do the same thing for a no. of epochs (outer loop) and calculating loss of each epochs. Mind that har epoch ke saath loss decrease hona chaiye

In [ ]:
#Sidha epoch implementaion from start

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  loss = []
  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1)
    y = df[['lpa']].values[j][0]

    #Parameter initialization

    y_hat, A1 = L_layer_forward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)

    loss.append(np.square(y-y_hat))

  print('Epoch - ', i+1, 'Loss = ', np.array(loss).mean())

Epoch -  1 Loss =  25.321744156025517
Epoch -  2 Loss =  18.320004165722047
Epoch -  3 Loss =  9.473661050729628
Epoch -  4 Loss =  3.2520938634031613
Epoch -  5 Loss =  1.3407132589299962


In [ ]:
parameters

{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

## Same thing using KERAS library

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2, activation = 'linear', input_dim = 2))
model.add(Dense(1, activation = 'linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[ 0.82858527,  0.6742492 ],
        [-0.0632211 , -0.7474797 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.3842039],
        [ 0.8703557]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype = np.float32),
               np.array([0., 0.], dtype = np.float32),
               np.array([[0.1], [0.1]], dtype = np.float32),
               np.array([0.], dtype = np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error', optimizer = optimizer)

In [ ]:
model.fit(df.iloc[:, :-1].values, df.iloc[:, -1].values, epochs = 67, verbose = 1, batch_size = 1)

Epoch 1/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0089 
Epoch 2/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0079
Epoch 3/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0082
Epoch 4/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0049
Epoch 5/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0020
Epoch 6/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0031
Epoch 7/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9990
Epoch 8/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0006 
Epoch 9/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9957 
Epoch 10/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9938 
Epoch 11/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9934 
Epoch 12/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9905 
Epoch 13/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9884 
Epoch 14/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9859 
Epoch 15/67
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9854 
Epoch 16/67
4/4 ━━━━━━━━━━━━━━━━━━

In [ ]:
model.get_weights()

[array([[0.3469081 , 0.3469081 ],
        [0.41968882, 0.41968882]], dtype=float32),
 array([0.29281536, 0.29281536], dtype=float32),
 array([[0.39951113],
        [0.39951113]], dtype=float32),
 array([0.21617058], dtype=float32)]

# **Backpropagation for Classification problems**

Change-
1. activation function taken sigmoid instead of linear

2. loss function taken binary cross entropy instead of mse

In [ ]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

     parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
     parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [ ]:
#Utility function
def sigmoid(Z):

  A = 1/(1+np.exp(-Z))

  return A

In [ ]:
def sigmoid_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b
  A = sigmoid(Z)

  return A

In [ ]:
def S_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2  #no. of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]

    A = sigmoid_forward(A_prev, W1, b1)

  return A, A_prev

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X):
  # notes dekho uske formulaes hi code me badle hain

  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * (y - y_hat) * parameters['W2'][0][0] * A1[0][0] * (1-A1[0][0]) * X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * (y - y_hat) * parameters['W2'][0][0] * A1[0][0] * (1-A1[0][0]) * X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * (y - y_hat) * parameters['W2'][0][0] * A1[0][0] * (1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * (y - y_hat) * parameters['W2'][1][0] *A1[1][0] * (1-A1[1][0]) * X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * (y - y_hat) * parameters['W2'][1][0] *A1[1][0] * (1-A1[1][0]) * X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * (y - y_hat) * parameters['W2'][1][0] *A1[1][0] * (1-A1[1][0]))

  return parameters


In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])

y_hat,A1 = S_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters, y, y_hat, A1, X)

print('Loss individual: ', -(y*np.log(y_hat) + (1-y)*np.log(1-y_hat)))

parameters

Loss individual:  0.11419159781855903


{'W1': array([[0.10039783, 0.10039783],
        [0.10039783, 0.10039783]]),
 'b1': array([[4.9728154e-05],
        [4.9728154e-05]]),
 'W2': array([[0.10287753],
        [0.10287753]]),
 'b2': array([[0.10633603]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[1][0]

parameters = initialize_parameters([2,2,1])

y_hat,A1 = S_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters, y, y_hat, A1, X)

print('Loss individual: ', -(y*np.log(y_hat) + (1-y)*np.log(1-y_hat)))

parameters

Loss individual:  -0.05221207920822568


{'W1': array([[0.100517, 0.100517],
        [0.100517, 0.100517]]),
 'b1': array([[6.46251686e-05],
        [6.46251686e-05]]),
 'W2': array([[0.10370955],
        [0.10370955]]),
 'b2': array([[0.10816804]])}

In [ ]:
#Sidha epoch implementaion from start

parameters = initialize_parameters([2,2,1])
epochs = 10

for i in range(epochs):

  loss = []
  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1)
    y = df[['lpa']].values[j][0]

    #Parameter initialization

    y_hat, A1 = S_layer_forward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)

    loss.append(np.square(y-y_hat))

  print('Epoch - ', i+1, 'Loss = ', np.array(loss).mean())

Epoch -  1 Loss =  25.583272528019364
Epoch -  2 Loss =  25.428291163340294
Epoch -  3 Loss =  25.3180268925321
Epoch -  4 Loss =  25.207285973032597
Epoch -  5 Loss =  25.096216829278205
Epoch -  6 Loss =  24.98501086285074
Epoch -  7 Loss =  24.8738925056021
Epoch -  8 Loss =  24.763108750271194
Epoch -  9 Loss =  24.652918939590762
Epoch -  10 Loss =  24.54358543646837


## Using KERAS

In [ ]:
model = Sequential()

model.add(Dense(2, activation = 'sigmoid', input_dim = 2))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[ 0.7124543 , -0.4397859 ],
        [-0.14059222, -0.6624528 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.2635045],
        [-1.0810859]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype = np.float32),
               np.array([0., 0.], dtype = np.float32),
               np.array([[0.1], [0.1]], dtype = np.float32),
               np.array([0.], dtype = np.float32)]

In [ ]:
model.set_weights(new_weights)
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'binary_crossentropy', optimizer = optimizer)

In [ ]:
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs = 10, verbose = 1, batch_size = 1)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: -6.5363 
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: -6.5872 
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -6.6438 
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: -6.6980
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -6.7542 
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -6.8087
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: -6.8583 
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: -6.9188 
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -6.9697 
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -7.0256 


I don't know why the loss in both approaches has this much difference. Maybe some formula def error or something, i haven't figured it out yet.